### ISSUE TITLE
Create v2.0 branch

### ISSUE THREAD

**Issue by thekaveman** [openmobilityfoundation/mds-openapi#16]
Requires the following issues to be complete:

- [x] #6 
- [x] #7 
- [x] #8 
- [x] #9 
- [x] #10 
- [x] #11 

## Tasks

- [x] Create a new branch from `main`, called `v2.0`
- [x] Make the new branch the default branch in this repository
- [x] In the Stoplight project, track the new branch and make it the default

**Comment by schnuerle** [comment]
I can finish this work once the OpenAPI work is complete and the MDS release is approved and ready.

**Comment by schnuerle** [comment]
All issues in the MDS repo are resolved. All issues in this repo are resolved besides this one.

I removed the 'draft' language from this repo's main readme and the docs readme (for Stoplight).

Anything else to do?

Also Stoplight is now upgraded to the Basic annual plan with more features.

**Comment by thekaveman** [comment]
@schnuerle I think everything looks good from my end! These 3 steps seem like the final pieces to make the OpenAPI "official" for 2.0

**Comment by schnuerle** [comment]
Done, amazing work, thanks for all of your help and skills!
